name: "Shopify Theme Push"
description: "Push theme to Shopify"
inputs:
    store:
        required: true
    theme_id:
        required: true
    token:
        required: true
    path:
        default: ./dist
    allow_live:
        default: "0"
    nodelete:
        default: "1"
runs:
    using: "composite"
    steps:
        - run: |
              shopify theme push \
                --store "${{ inputs.store }}" \
                --theme "${{ inputs.theme_id }}" \
                --password "${{ inputs.token }}" \
                --path "${{ inputs.path }}" \
                $([ "${{ inputs.allow_live }}" == "1" ] && echo "--allow-live") \
                $([ "${{ inputs.nodelete }}" == "1" ] && echo "--nodelete")
          shell: bash
