name: "Shopify Theme Push"
description: "Push theme to Shopify"
inputs:
  store:
    required: true
  theme_id:
    required: true
  token:
    required: true
  path:
    default: ./dist
  allow_live:
    default: "false"
  nodelete:
    default: "true"
runs:
  using: "composite"
  steps:
    - run: |
        shopify theme push \
          --store "${{ inputs.store }}" \
          --theme "${{ inputs.theme_id }}" \
          --password "${{ inputs.token }}" \
          --path "${{ inputs.path }}" \
          $([ "${{ inputs.allow_live }}" == "true" ] && echo "--allow-live") \
          $([ "${{ inputs.nodelete }}" == "true" ] && echo "--nodelete")
      shell: bash
