name: "Upload Artifact"
description: "Upload a folder or file as GitHub Action artifact"
inputs:
  name:
    required: true
  path:
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
        if-no-files-found: error
