name: "Shopify Theme Lighthouse"
description: "Runs Shopify Lighthouse CI against a theme root"
inputs:
  access_token:
    required: true
  store:
    required: true
  lhci_github_app_token:
    required: true
  theme_root:
    required: true
runs:
  using: "composite"
  steps:
    - uses: shopify/lighthouse-ci-action@v1
      with:
        access_token: ${{ inputs.access_token }}
        store: ${{ inputs.store }}
        lhci_github_app_token: ${{ inputs.lhci_github_app_token }}
        theme_root: ${{ inputs.theme_root }}
