name: "Shopify Theme Delete"
description: "Deletes a Shopify theme by id"
inputs:
    store:
        required: true
    theme_id:
        required: true
    token:
        required: true
runs:
    using: "composite"
    steps:
        - run: |
              set -euo pipefail
              shopify theme delete \
                  --store "${{ inputs.store }}" \
                  --theme "${{ inputs.theme_id }}" \
                  --password "${{ inputs.token }}" \
                  --force \
                  --no-color
          shell: bash
