name: "Zip Folder"
description: "Zip a folder into an archive"
inputs:
    folder:
        required: true
    output:
        required: true
runs:
    using: "composite"
    steps:
        - run: |
              cd "${{ inputs.folder }}"
              zip -r "../${{ inputs.output }}" .
              cd ..
          shell: bash
