name: Shopify Theme CI
on:
  push:
    branches:
      - dev
      - production

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: iamota/iamota-github-actions/.github/actions/shopify-backup@v1
        with:
          use_themekit: "${{ vars.SHOPIFY_THEME_KIT }}"
          store: "${{ vars.SHOPIFY_FLAG_STORE }}"
          theme_id: "${{ vars.SHOPIFY_FLAG_THEME_ID }}"
          token: "${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}"
          bucket: "${{ vars.AWS_S3_BUCKET_SHOPIFY_BACKUPS }}"
          aws_key: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws_secret: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"

  deploy:
    runs-on: ubuntu-latest
    needs: backup
    steps:
      - uses: actions/checkout@v4

      - run: npm ci && npm run build

      - uses: iamota/iamota-github-actions/.github/actions/shopify-push@v1
        with:
          use_themekit: "${{ vars.SHOPIFY_THEME_KIT }}"
          store: "${{ vars.SHOPIFY_FLAG_STORE }}"
          theme_id: "${{ vars.SHOPIFY_FLAG_THEME_ID }}"
          token: "${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}"
          path: "./dist"
          ignore: "${{ vars.SHOPIFY_FLAG_IGNORE }}"
          allow_live: "${{ vars.SHOPIFY_FLAG_ALLOW_LIVE }}"
          nodelete: ""
