name: Shopify Theme Backup + Deploy

on:
    workflow_call:
        inputs:
            branch:
                type: string
                required: true
            theme_src:
                type: string
                required: false
                default: "."
            theme_dist:
                type: string
                required: false
                default: ""
            theme_path:
                type: string
                required: false
                default: ""
            build_install_command:
                type: string
                required: false
                default: "npm ci"
            build_command:
                type: string
                required: false
                default: "npx webpack --env target=${GITHUB_BRANCH}"
            aws_region:
                type: string
                required: false
                default: "us-west-2"
            aws_s3_bucket:
                type: string
                required: false
                default: ""
        secrets:
            SHOPIFY_STORE:
                required: true
            SHOPIFY_THEME_ID:
                required: true
            SHOPIFY_THEME_ACCESS_TOKEN:
                required: true
            AWS_ACCESS_KEY_ID:
                required: false
            AWS_SECRET_ACCESS_KEY:
                required: false

permissions:
    contents: read

concurrency:
    group: iamota-shopify-backup-deploy-${{ inputs.branch }}
    cancel-in-progress: true

jobs:
    backup:
        uses: ./.github/workflows/shopify-backup.yml
        with:
            branch: ${{ inputs.branch }}
            aws_region: ${{ inputs.aws_region }}
            aws_s3_bucket: ${{ inputs.aws_s3_bucket }}
        secrets:
            SHOPIFY_STORE: ${{ secrets.SHOPIFY_STORE }}
            SHOPIFY_THEME_ID: ${{ secrets.SHOPIFY_THEME_ID }}
            SHOPIFY_THEME_ACCESS_TOKEN: ${{ secrets.SHOPIFY_THEME_ACCESS_TOKEN }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    deploy:
        needs: [backup]
        uses: ./.github/workflows/shopify-deploy.yml
        with:
            branch: ${{ inputs.branch }}
            theme_src: ${{ inputs.theme_src }}
            theme_dist: ${{ inputs.theme_dist }}
            theme_path: ${{ inputs.theme_path }}
            build_install_command: ${{ inputs.build_install_command }}
            build_command: ${{ inputs.build_command }}
        secrets:
            SHOPIFY_STORE: ${{ secrets.SHOPIFY_STORE }}
            SHOPIFY_THEME_ID: ${{ secrets.SHOPIFY_THEME_ID }}
            SHOPIFY_THEME_ACCESS_TOKEN: ${{ secrets.SHOPIFY_THEME_ACCESS_TOKEN }}
